---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loot-data
spec:
  selector:
    matchLabels:
      run: loot-data
  replicas: 1
  template:
    metadata:
      labels:
        run: loot-data
    spec:
      containers:
      - name: loot-data
        image: okteto.dev/loot-data
        ports:
        - containerPort: 8081
        env:
        - name: DEMO_ENABLE_FULL_DATA
          value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: loot-data
  labels:
    run: loot-data
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: loot-data