---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api
spec:
  selector:
    matchLabels:
      run: client-api
  replicas: 1
  template:
    metadata:
      labels:
        run: client-api
    spec:
      containers:
      - name: client-api
        image: okteto.dev/client-api
        ports:
        - containerPort: 8080
        env:
        - name: LOOT_DATA_ENDPOINT
          value: "loot-data.staging:8081"

---
apiVersion: v1
kind: Service
metadata:
  name: client-api
  labels:
    run: client-api
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: client-api
