// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package loot_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LootRPCClient is the client API for LootRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LootRPCClient interface {
	LootDescription(ctx context.Context, in *LootDescriptionRequest, opts ...grpc.CallOption) (*LootDescriptionResponse, error)
}

type lootRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLootRPCClient(cc grpc.ClientConnInterface) LootRPCClient {
	return &lootRPCClient{cc}
}

func (c *lootRPCClient) LootDescription(ctx context.Context, in *LootDescriptionRequest, opts ...grpc.CallOption) (*LootDescriptionResponse, error) {
	out := new(LootDescriptionResponse)
	err := c.cc.Invoke(ctx, "/lootpb.LootRPC/LootDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LootRPCServer is the server API for LootRPC service.
// All implementations must embed UnimplementedLootRPCServer
// for forward compatibility
type LootRPCServer interface {
	LootDescription(context.Context, *LootDescriptionRequest) (*LootDescriptionResponse, error)
	mustEmbedUnimplementedLootRPCServer()
}

// UnimplementedLootRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLootRPCServer struct {
}

func (UnimplementedLootRPCServer) LootDescription(context.Context, *LootDescriptionRequest) (*LootDescriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LootDescription not implemented")
}
func (UnimplementedLootRPCServer) mustEmbedUnimplementedLootRPCServer() {}

// UnsafeLootRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LootRPCServer will
// result in compilation errors.
type UnsafeLootRPCServer interface {
	mustEmbedUnimplementedLootRPCServer()
}

func RegisterLootRPCServer(s grpc.ServiceRegistrar, srv LootRPCServer) {
	s.RegisterService(&LootRPC_ServiceDesc, srv)
}

func _LootRPC_LootDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LootDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LootRPCServer).LootDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lootpb.LootRPC/LootDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LootRPCServer).LootDescription(ctx, req.(*LootDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LootRPC_ServiceDesc is the grpc.ServiceDesc for LootRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LootRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lootpb.LootRPC",
	HandlerType: (*LootRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LootDescription",
			Handler:    _LootRPC_LootDescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loot.proto",
}
